### PR TITLE
Moved add_magnetic_field_covariance from OnUpdate to Load

### LINKED ISSUE #12975: Slowing real time factor in SITL Gazebo
Hello,

I am doing a 3 IRIS quadcopters simulation in gazebo.
I have noticed that after running simulation for 4 days at low quadcopters speed (1 m/s), and after updating to the last SITL commit in which iris SDF file has been update with new plugins for magnometers and gyroscope, that gazebo is slowing down, the real time factor is going down to 0.22
Also the communication between the SDK and the PX4 is slowing. I am even losing heart beats during take off and landing.
The output from the SDK  is the following :
```
11:06:27|Debug] MAVLink: info: DISARMED by auto disarm on land (system_impl.cpp:300)
[11:06:28|Info ] heartbeats timed out (system_impl.cpp:305)
[11:06:28|Debug] Lost 5283920058631409232 (mavsdk_impl.cpp:388)
[11:06:29|Info ] heartbeats timed out (system_impl.cpp:305)
[11:06:29|Info ] heartbeats timed out (system_impl.cpp:305)
[11:06:29|Debug] Lost 5283920058631409233 (mavsdk_impl.cpp:388)
[11:06:29|Debug] Lost 5283920058631409234 (mavsdk_impl.cpp:388)
[11:06:29|Debug] Discovered 1 component(s) (UUID: 5283920058631409232) (system_impl.cpp:557)
[11:06:29|Info ] Discovered system with UUID: 5283920058631409232
[11:06:31|Debug] Discovered 1 component(s) (UUID: 5283920058631409233) (system_impl.cpp:557)
[11:06:31|Info ] Discovered system with UUID: 5283920058631409233
[11:06:31|Debug] Discovered 1 component(s) (UUID: 5283920058631409234) (system_impl.cpp:557)
[11:06:31|Info ] Discovered system with UUID: 5283920058631409234
[11:06:32|Info ] heartbeats timed out (system_impl.cpp:305)
[11:06:32|Debug] Lost 5283920058631409232 (mavsdk_impl.cpp:388)
[11:06:34|Info ] heartbeats timed out (system_impl.cpp:305)
[11:06:34|Debug] Lost 5283920058631409233 (mavsdk_impl.cpp:388)
[11:06:34|Info ] heartbeats timed out (system_impl.cpp:305)
[11:06:34|Debug] Lost 5283920058631409234 (mavsdk_impl.cpp:388)
[11:06:34|Debug] Discovered 1 component(s) (UUID: 5283920058631409232) (system_impl.cpp:557)
[11:06:34|Info ] Discovered system with UUID: 5283920058631409232
[11:06:35|Debug] Discovered 1 component(s) (UUID: 5283920058631409233) (system_impl.cpp:557)
[11:06:35|Info ] Discovered system with UUID: 5283920058631409233
[11:06:35|Debug] Discovered 1 component(s) (UUID: 5283920058631409234) (system_impl.cpp:557)
[11:06:35|Info ] Discovered system with UUID: 5283920058631409234

```
I am using Arch Linux with 2 Intel(R) Xeon(R) CPU E5-2609 v4 @ 1.70GHz with 16 cores and 32 GB of RAM.

Also using `htop`, I have noticed that `gzserver` is using only 70% of only one core of CPU, there is no over consumption at any level, even though it is a little bit reduced over the four days

Does any one have an idea about what is happening??

### LINKED ISSUE #14189: SITL gazebo real time factor is slowing down for plane
**Describe the bug**
The real time factor for a simple plane simulation progressively slows down. From about 16 to 5 in 10 minutes. Similar to [#12975](https://github.com/PX4/Firmware/issues/12975)

**To Reproduce**
Firmware version 10.0
Gazebo 9.0

```
git checkout v1.10.0
git submodule update --init --recursive
pip install jinja2 empy catkin_pkg toml numpy
export PX4_SIM_SPEED_FACTOR=20
make px4_sitl gazebo_plane
```
Then in the px4 console:
```
pxh> commander takeoff
```

**Expected behavior**
The real time factor goes down consistently. 

**Log Files and Screenshots**
*Always* provide a link to the flight log file:
Log files and gz stats are available to the following link:
[Log files](https://drive.google.com/drive/folders/1aN8FYOeleXipdWKhOEPBMHR30sqFBS6t?usp=sharing)

### PR DESCRIPTION
**Pull request by tnkkk**
Fixes https://github.com/PX4/Firmware/issues/14189, fixes: https://github.com/PX4/Firmware/issues/12975

### CODE REVIEW

File: src/gazebo_magnetometer_plugin.cpp [hunk 1]
```diff
@@ -195,18 +207,6 @@ void MagnetometerPlugin::OnUpdate(const common::UpdateInfo&)
...
-        // principal diagonal = the variance of the random variables
-        // = noise_density²
-        case 0: case 4: case 8:
-          mag_message_.add_magnetic_field_covariance(noise_density_ * noise_density_);
-          break;
-        default:
-          mag_message_.add_magnetic_field_covariance(0.0);
-      }
-    }
-
```
Comment (Jaeyoung-Lim) [inline src/gazebo_magnetometer_plugin.cpp:209]: Wouldn't it be better if we should keep it where it is, but use `set_magnetic_field_covariance` instead of `add_magnetic_field_covariance`?

**Review by Jaeyoung-Lim — CHANGES_REQUESTED** [review]

File: src/gazebo_magnetometer_plugin.cpp (hunk 1 above)
Comment (julianoes) [reply src/gazebo_magnetometer_plugin.cpp:209]: @Jaeyoung-Lim actually I agree with this solution because `noise_density_` is loaded once in `Load` and doesn't change after that.

**Review by julianoes — APPROVED** [review]
I'd say let's merge it.

**Review by Jaeyoung-Lim — APPROVED** [review]
