### PR TITLE
Fix gimbal pointing backwards

### LINKED ISSUE #14902: Typhoon h480 gimbal direction
Hi, I firstly run the sitl with typhoon h480 that following instruction.

http://dev.px4.io/master/en/simulation/gazebo.html

To simulate Typhoon, I use the command

**make px4_sitl gazebo_typhoon_h480**

However, when the gazebo turn on the gimbal looks back of the uav.
What's the problem and how do I resolve it?

Screenshot from 2020-05-14 21-09-11

Thank you.

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR fixes https://github.com/PX4/Firmware/issues/14902, where the gimbal was pointing backwards. 

@julianoes @TSC21 It seems like the problem is that we transform the yaw command, and not the actual gimbal orientation to the correct frame. While this is not a "fix", nevertheless I would like to have this fix in so that the end user does not suffer from the issue.

I will try to fix it properly in the meantime

### CODE REVIEW

File: src/gazebo_gimbal_controller_plugin.cpp [hunk 1]
```diff
@@ -483,7 +483,7 @@ void GimbalControllerPlugin::OnUpdate()
     double dt = (time - this->lastUpdateTime).Double();
 
     // We want yaw to control in body frame, not in global.
-    double yaw_command = this->yawCommand + this->lastImuYaw;
+    double yaw_command = this->yawCommand + this->lastImuYaw + M_PI;
```
Comment (TSC21) [inline src/gazebo_gimbal_controller_plugin.cpp]: This still doesn't seem well explained.

Comment (Jaeyoung-Lim) [reply src/gazebo_gimbal_controller_plugin.cpp]: I think the fix should be done by transforming the gimbal orientation in the bodyframe and not by adding the orientation to the command itself. I will try to fix it properly, but this is something that we can hide the issue from the end user

Comment (TSC21) [reply src/gazebo_gimbal_controller_plugin.cpp]: Right. So why not use the body frame orientation quaternion directly? You can create a quaternion of the yaw command, apply the rotation and extract yaw.

Comment (Jaeyoung-Lim) [reply src/gazebo_gimbal_controller_plugin.cpp]: Ah, right. That might be easier. I was trying to keep the yaw command and make everything else in bodyframe

**Comment by Jaeyoung-Lim** [comment]
I realized that the typhoon has the imu rotated by PI on the yaw axis and since the gimbal plugin is subscribing to the vehicle imu topic directly, this makes the gimbal point into the wrong direction: https://github.com/PX4/sitl_gazebo/blob/master/models/typhoon_h480/typhoon_h480.sdf#L678

**Comment by Jaeyoung-Lim** [comment]
@TSC21 @julianoes I have fixed this by adding attitude information to the groundtruth message and then use that to get the vehicle orientation instead of the imu message. I realized that this breaks when the imu orientation is no the same as vehicle orientation

**Review by TSC21 — APPROVED** [review]
