### PR TITLE
Fix airspeed sensor wind subscription

### LINKED ISSUE #556: Wind not reflected in airspeed
@Jaeyoung-Lim Following #552 the windy world now works for VTOLs, but the airspeed reading does not take into account the wind.

Log here:
https://logs.px4.io/plot_app?log=c130f864-5dfb-41c2-a077-b9a9c2abdc59
image

I have changed the wind to 6m/s mean and -1 0 0 direction in the windy.world file. During the MC climb it should therefore indicate an offset between ground speed and airspeed of approx 5m/s. Also during the FW part there is never such an offset. From the behaviour of the drone the wind is present in the simulation, but it's not reflected in the airspeed: the drone gets pushed back in MC climb and it also yaws into the wind in FW mode.

PX4 at current master (a93052f9b2)
sitl_gazebo at current master (89755a1)
Simulation started with `HEADLESS=1 make px4_sitl gazebo_standard_vtol__windy`

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
While wind topic names have been fixed in https://github.com/PX4/sitl_gazebo/pull/552, airspeed sensor was still subscribing to the wrong topic name. 

Fixes https://github.com/PX4/sitl_gazebo/issues/556

### CODE REVIEW

File: src/gazebo_airspeed_plugin.cpp [hunk 1]
```diff
@@ -84,7 +84,7 @@ void AirspeedPlugin::Load(physics::ModelPtr _model, sdf::ElementPtr _sdf)
       boost::bind(&AirspeedPlugin::OnUpdate, this, _1));
 
   airspeed_pub_ = node_handle_->Advertise<sensor_msgs::msgs::Airspeed>("~/" + model_->GetName() + "/airspeed", 10);
-  wind_sub_ = node_handle_->Subscribe("~/" + model_->GetName() + "/wind", &AirspeedPlugin::WindVelocityCallback, this);
+  wind_sub_ = node_handle_->Subscribe("~/world_wind", &AirspeedPlugin::WindVelocityCallback, this);
```
Comment (LorenzMeier) [inline src/gazebo_airspeed_plugin.cpp:87]: Is this factoring in the wind direction correctly?

Comment (Jaeyoung-Lim) [reply src/gazebo_airspeed_plugin.cpp:87]: As far as I am concerned yes, it used to work correctly before but stopped subscribing to the wind topic with the latest commit

**Review by LorenzMeier — APPROVED** [review]

**Comment by ThomasRigi** [comment]
The wind direction isn't completely correct. It works with wind blowing from the East (first log), but not for wind blowing from the south (second log)

https://logs.px4.io/plot_app?log=077852f0-e6e5-4a4f-a3e0-c863b6c44020

 https://logs.px4.io/plot_app?log=4b8f4d83-35a5-450e-bd74-3758cf1256ad

On the second log the drone flies with back wind from 1:05-1:15, for example. But the airspeed is higher than the ground speed.

**Comment by LorenzMeier** [comment]
Ok, so what we're missing is the rotation around the body frame, as I was originally concerned. @ThomasRigi Could you contribute that? Given that you're anyway spending time on this, adding it would be fairly trivial and you're in the best position to validate. We really need those contributions from the people most affected, because the maintainers can't do all the development.

**Comment by ThomasRigi** [comment]
Coordinate transformations have always been my nemesis, so I'm not sure how easy I will find it. :sweat_smile: 
I'll try to find some time this week to look into it.
